### ISSUE TITLE
Please post the source code.

### ISSUE THREAD

**Issue by nissimzur** [DFRobot/uPyCraft#1]
Please post the source code.
What the point of apps if no one can contribute to it?

**Comment by ouki-wang** [comment]
@nissimzur thanks for your suggestion
We will post the source code after app stabilization, possibly in December.

**Comment by Avi-TelnT** [comment]
The Idea is that we can help in apps debug and improve it too. 
So, please update it now, it still a good point to start and no need to wait to December.
I can send you many examples of esp32 code, you can add too. 
Thank you
nissim.zur@gmail.com

**Comment by elf55** [comment]
GITHub is not meant to be a repository for closed source executables.

**Comment by vanminh0910** [comment]
uPyCraft is a good tool and it's good to publish the source code so that everyone can contribute. By doing that, you gain the trust from community and make it more popular in uPython community.

**Comment by nbxtruong** [comment]
This is the end of December. So, When do you open the source code?

**Comment by nbxtruong** [comment]
@Avi-TelnT Do you have example for AWS IoT? That mean, How to Public and Subscribe a Topic by using MQTT? and how to update/get Thing Shadows?

Thank you so much ;)

**Comment by Avi-TelnT** [comment]
I do not have....
This is demo from some loboris mP. I never tested it.

def conncb(task):
    print("[{}] Connected".format(task))

def disconncb(task):
    print("[{}] Disconnected".format(task))

def subscb(task):
    print("[{}] Subscribed".format(task))

def pubcb(pub):
    print("[{}] Published: {}".format(pub[0], pub[1]))

def datacb(msg):
    print("[{}] Data arrived from topic: {}, Message:\n".format(msg[0], msg[1]), msg[2])
mqtt = network.mqtt("loboris", "loboris.eu", user="wifimcu", password="wifimculobo", cleansession=True, connected_cb=conncb, disconnected_cb=disconncb, subscribed_cb=subscb, published_cb=pubcb, data_cb=datacb)



mqtts = network.mqtt("eclipse", "iot.eclipse.org", secure=True, cleansession=True, connected_cb=conncb, disconnected_cb=disconncb, subscribed_cb=subscb, published_cb=pubcb, data_cb=datacb)

**Comment by NanaWangDFR** [comment]
@nbxtruong   Well, the deadline is 12th, December. We are still regulating the codes. Thanks for your note.

**Comment by nbxtruong** [comment]
Thank you @NanaWangDFR, I am waiting for it. I hope it can run fine on ubuntu.

**Comment by ouki-wang** [comment]
@nbxtruong @Avi-TelnT @vanminh0910 @nissimzur come to check the source code!
https://github.com/DFRobot/uPyCraft_src

**Comment by mrgithub** [comment]
You should put the source in /uPyCraft it will make it easier for everyone to find it

**Comment by Avi-TelnT** [comment]
@ouki-wang
Thank you for your great work.
You describe how to run it? or convert to exe?

**Comment by ouki-wang** [comment]
@Avi-TelnT @mrgithub We are writing readme.md, which will describe the way to run with python Idel and pack src to .exe in detail.

**Comment by Avi-TelnT** [comment]
Thank you.

**Comment by nbxtruong** [comment]
Thank you @ouki-wang I am going to check it.
