### ISSUE TITLE
Error on upload files with ' ... '

### ISSUE THREAD

**Issue by JK-de** [DFRobot/uPyCraft#10]
Using version 0.30 on ESP32 with MicroPython 1.9.1.

If I have a file with " ... " (`<space><point><point><point><space>`) inside like
```Python
# Lorem ... ipsum
```
the upload ends with
```
Ready to download this file,please wait!
.
download false6
```
and the file is empty.

Note: removing a point or space and the transmission works.

**Comment by jhlucky** [comment]
Can you capture and show your program.
In addition, you can try 0.29 uPyCraft or restart the ide.

**Comment by xmoiduts** [comment]
This file will result in a failed upload: https://gist.github.com/nevercast/9c48505cc6c5687af59bcb4a22062795

**Comment by McMoes** [comment]
I can confirm that. I can not even upload a file with print('...')
