### ISSUE TITLE
file cannot be opened from the left sidebar (v0.30)

### ISSUE THREAD

**Issue by dukeduck1984** [DFRobot/uPyCraft#12]
the .py file under workSpace cannot be opened from the left sidebar (nothing happened when double clicked).  if opened from “File --> Open”, the title of file name is in blue and there is a chip icon indicating the file is stored in the device but actually it is not.  v0.30, win10.  it's fine in v0.29.

**Comment by jhlucky** [comment]
This is a bug,next version will fix it. now, you can set workspace in C dict,which works well.
