### ISSUE TITLE
ESP32 蓝牙部分的详细API或者源码哪里能找到

### ISSUE THREAD

**Issue by LGinC** [DFRobot/uPyCraft#3]
uPyCraft 官方文档中对于这部分的描述实在是太....简略了
我需要详细了解蓝牙部分的API

**Comment by ouki-wang** [comment]
@LGinC 请参考这个地址：https://github.com/MrSurly/micropython-esp32/blob/dev-bluetooth/esp32/bluetooth_docs.md

**Comment by Avi-TelnT** [comment]
Thank you  @ouki-wang
Can you offer how to run the code the on windows? or convert it to exe?
