### ISSUE TITLE
PermissionError

### ISSUE THREAD

**Issue by Kabron287** [DFRobot/uPyCraft#6]
V0.29 Windows 10 x64
Boards: Wrover Kit V3 and M5STACK with MicroPython_ESP32_psRAM_LoBo-master flashed
Every time I try to open port uPyCraft suggests to reflash board.
If I cancel it, on the next attempt I got **PermissionError.**
Once or twice I could connect to board, but do not notice  regularity.

**Comment by ouki-wang** [comment]
@Kabron287 
The current version do not suport M5STACT.
