### ISSUE TITLE
Delete not work

### ISSUE THREAD

**Issue by Kabron287** [DFRobot/uPyCraft#7]
Content Delete Menu

`os.listdir('./recorder.py')`
`Traceback (most recent call last):`
  `File "<stdin>", line 1, in <module>`
`OSError: 20`
`>>>`
`rm dir false`

Manually os.remove('recorder.py') works.

**Comment by ouki-wang** [comment]
@Kabron287 os.listdir(path), the parameter should be a path, not filename.

**Comment by ouki-wang** [comment]
@Kabron287 If you want to delete file folders, you must ensure they are empty; if they are not, you must delete contents then can you delete the  file folders.
