### ISSUE TITLE
uPyCraft.exe not working windows 10

### ISSUE THREAD

**Issue by MichaelGGH** [DFRobot/uPyCraft#9]
Hello,

when i try to run the uPyCraft.exe on Windows 10 I get error:

code can't be executed because MSVCR100.dll not found.

What am I doing wrong? I trieed multiple download links from the internet.

![grafik](https://user-images.githubusercontent.com/36878197/39477592-fe1edbe8-4d5f-11e8-9775-9e3f1ab65639.png)

**Comment by ouki-wang** [comment]
We have already tested uPyCraft in 64bit and 32bit win10, the result is alright. Could you please figure out the PC type? Well, you can also try downloading the new version: uPyCraft_V0.30.exe.

**Comment by jhlucky** [comment]
You can download this component by yourself.

**Comment by MichaelGGH** [comment]
Thank you very much for replying,

I forgot to mention that im on Windows 10 Pro.

Not sure what a machine Type is, this is my build:
Windows 10 Pro Version 1709
CPU: Ryzen 5 1600x
Motherboard: MSI B350 Gamming Pro Carbon
RAM: 16 GB  
One HDD and one SSD
Nvidia 1060 GPU

I downloaded the hole repository. But uPyCraft.exe and uPyCraft_V0.30.exe both bring the error.

![grafik](https://user-images.githubusercontent.com/36878197/39536452-ecd70d38-4e36-11e8-877a-cb480c9e64d2.png)

**Comment by jhlucky** [comment]
@MichaelGGH In the package of uPyCraft, it haven't packed dll files. Which means your computer lacks of this library, you should download the library first then execute uPyCraft. If you still cannot open uPyCraft when the dll files has already be downloaded, I will help you to test the system as yours then try again.

**Comment by MichaelGGH** [comment]
Thank you very much for your relply. It solved the issue. 

I had to install: 

Microsoft Visual C++ 2010 Redistributable Package (x86) 
Microsoft Visual C++ 2010 Redistributable Package (x64) 

Now I can start the uPyCraft.exe

Turned out that the file was not missing from the download but from my system just like you said.
Googel missing MSVCR100.dll could have solved the problem. But I did not now what a .dll is and
asumed that is a file from the uPycraft project.

sorry for me beeing a noob and thanks to everyone.

**Comment by Jibun-no-Kage** [comment]
On Windows 11 Pro, even with install of Microsoft Visual C++ 2010 SP1, no joy.  How about authors of uPyCraft help out here?

**Comment by peterk62** [comment]
Windows 11 home - 64 bit OS. I installed the 64 bit redist package, but no joy. Installing the 32 bit redist package made it work.

**Comment by Hdekkers-hwd** [comment]
Windows 11 pro , I tried to install upycraft v1.0 and 1.1. First the install told me that file MSVCR100.dll was missing. After installing Microsoft Visual C++ 2010 Redistributable Package (x64) i revceive the message: "toepassingsfout 0xc000007b on both versions. Any idea what is missing?
